name: flutter_nfc_kit
description: Plugin to provide NFC functionality on Android and iOS, including reading metadata and transceive layer 3 & 4 data with NFC tags / cards
version: 1.2.0
homepage: "https://github.com/nfcim/flutter_nfc_kit"

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.3
  json_serializable: ^3.2.5

flutter:
  plugin:
    androidPackage: im.nfc.flutter_nfc_kit
    pluginClass: FlutterNfcKitPlugin
