source "https://rubygems.byted.org"

gem 'EEScaffold', '>= 0.1.0.pre'
gem "cocoapods-flutter", "= 1.0.11"
gem "activesupport", "= 7.0.8"
gem 'bd_pod_extentions', '6.3.0' # 推荐 6.3.0
gem 'cocoapods-remote-resolve', '>=0.1.35' # 云端依赖分析插件<https://bytedance.feishu.cn/wiki/wikcnwGzMNwH9Tr0IRnewGedbMg?table=tblWxDArGaGo7yLE#>

cocoapods_version = '1.12.1'
gem 'cocoapods', cocoapods_version # 保证Bundle执行的和本地Podfile兼容
# 隔离cocoapod缓存环境. cocoapod发现版本不一样会清缓存，这样多个版本混用时会互相清除，造成并发问题。
ENV['CP_CACHE_DIR'] = File.join(Dir.home, "Library/Caches/CocoaPods", cocoapods_version)